FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY scripts/consume_records_to_db.py .
COPY .env .
CMD ["python", "consume_records_to_db.py"]
